language: go
sudo: false

services:
  - redis-server

matrix:
  include:
    - go: 1.5
    - go: 1.6
    - go: 1.7
    - go: 1.8
    - go: 1.9
    - go: tip
  allow_failures:
    - go: tip

install:
  - # skip

script:
  - export PATH=$PATH:$HOME/go/bin:/usr/local/go/bin
  - export GOPATH=$HOME/go
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go tool vet .
  - go test -v -race ./...
